version: '3.4'
services:
  h2:
    image: lxreact/users:h2
    container_name: lxreact-h2
    ports:
      - 9092:9092
      - 8082:8082
  api:
    image: lxreact/users:api
    container_name: lxreact-api
    depends_on:
      - h2
    links:
      - h2
    ports:
      - 8080:8080
    env_file:
      - application.properties.env